export const roleOptions = [
  { value: 'ENGINEERING', label: 'ENGINEERING', isDisabled: true },
  { value: 'backend', label: 'Backend' },
  { value: 'frontend', label: 'Frontend' },
  { value: 'fullstack', label: 'Fullstack' },
  { value: 'ios', label: 'IOS' },
  { value: 'flutter', label: 'Flutter' },
  { value: 'react native', label: 'React Native' },
  { value: 'android', label: 'Android' },
  { value: 'frontend', label: 'Frontend' },
  { value: 'dev-ops', label: 'Dev-Ops' },
  { value: 'data engineer', label: 'Data Engineer' },
  { value: 'data science', label: 'Data Science' },
  { value: 'computer-vision', label: 'Computer-Vision' },
  { value: 'nlp', label: 'Nlp' },
  { value: 'deep-learning', label: 'Deep-Learning' },
  { value: 'test / qa', label: 'Test / Qa' },
  { value: 'web3', label: 'Web3' },
  { value: 'sre', label: 'Sre' },
  { value: 'data-infrastructure', label: 'Data-Infrastructure' },
  { value: 'design', label: 'DESIGN', isDisabled: true },
  { value: 'designer', label: 'Designer' },
  { value: 'design manager', label: 'Design Manager' },
  { value: 'graphic designer', label: 'Graphic Designer' },
  { value: 'product designer', label: 'Product Designer' },
  { value: 'product', label: 'PRODUCT', isDisabled: true },
  { value: 'product manager', label: 'Product Manager' },
  { value: 'operations', label: 'OPERATIONS', isDisabled: true },
  { value: 'operations manager', label: 'Operations Manager' },
  { value: 'founder’s office/chief Of staff', label: 'Founder’s Office/Chief Of Staff' },
  { value: 'sales', label: 'SALES', isDisabled: true },
  { value: 'sales development representative', label: 'Sales Development Representative' },
  { value: 'account executive', label: 'Account Executive' },
  { value: 'account manager', label: 'Account Manager' },
  { value: 'marketing', label: 'MARKETING', isDisabled: true },
  { value: 'digital marketing manager', label: 'Digital Marketing Manager' },
  { value: 'growth hacker', label: 'Growth Hacker' },
  { value: 'marketing', label: 'Marketing' },
  { value: 'product marketing manager', label: 'Product Marketing Manager' },
  { value: 'other engineering', label: 'OTHER ENGINEERING', isDisabled: true },
  { value: 'mechanical', label: 'Mechnical' },
  { value: 'hardware', label: 'Hardware' },
  { value: 'systems', label: 'Systems' },
  { value: 'business analyst', label: 'BUSINESS ANALYST', isDisabled: true },
  { value: 'business analyst', label: 'Business Analyst' },
  { value: 'data analyst', label: 'DATA ANALYST', isDisabled: true },
  { value: 'data analyst', label: 'Data Analyst' },
  { value: 'project manager', label: 'PROJECT MANAGER', isDisabled: true },
  { value: 'project manager', label: 'Project Manager' },
  { value: 'management', label: 'MANAGEMENT', isDisabled: true },
  { value: 'management', label: 'Management' },
  { value: 'legal', label: 'LEGAL', isDisabled: true },
  { value: 'legal', label: 'Legal' },
  { value: 'hr', label: 'HR', isDisabled: true },
  { value: 'hr', label: 'Hr' },
  { value: 'finance', label: 'FINANCE', isDisabled: true },
  { value: 'finance', label: 'Finance' },
];

export const employesOptions = [
  { value: '1-10', label: '1-10' },
  { value: '11-20', label: '11-20' },
  { value: '21-50', label: '21-50' },
  { value: '51-100', label: '51-100' },
  { value: '101-200', label: '101-200' },
  { value: '201-500', label: '201-500' },
  { value: '500+', label: '500+' },
];

export const employeExperience = [
  { value: 1, label: '1' },
  { value: 2, label: '2' },
  { value: 3, label: '3' },
  { value: 4, label: '4' },
  { value: 5, label: '5' },
  { value: 6, label: '6' },
  { value: 7, label: '7' },
  { value: 8, label: '8' },
  { value: 9, label: '9' },
  { value: 10, label: '10' },
];

export const jobTypeOptions = [
  { value: 'remote', label: 'Remote' },
  { value: 'hybrid', label: 'Hybrid' },
  { value: 'in-office', label: 'In-Office' },
];

export const minbasePayOptions = [
  { value: '0L', label: '0L' },
  { value: '10L', label: '10L' },
  { value: '20L', label: '20L' },
  { value: '30L', label: '30L' },
  { value: '40L', label: '40L' },
  { value: '50L', label: '50L' },
  { value: '60L', label: '60L' },
  { value: '70L', label: '70L' },
];
